### ISSUE TITLE
Image and video posting options disappearing

### ISSUE THREAD

**Issue by Dingleberrytom** [lmj0011/holdup#22]
After selecting a subreddit from the dropdown, the options to post video and images disappear, leaving only three options in sight. 
![Screenshot_20230511-062357-621](https://github.com/lmj0011/holdup/assets/133221736/3f2addb4-5dcd-48ee-982f-cd04890eb954)
![Screenshot_20230511-062317-055](https://github.com/lmj0011/holdup/assets/133221736/e9150e2b-f4ca-4d21-9d3c-d8e1433649af)

**Comment by lmj0011** [comment]
That usually means the subreddit doesn't support those types of posts.

**Comment by lmj0011** [comment]
@Dingleberrytom Is this still an issue, and if so, what subreddit are you trying to post to? Given the icon in the screenshot, it looks like you are posting to a subreddit you created

**Comment by lmj0011** [comment]
closing due to no response from original poster.
